version: '3.4'
services:
  # back-end api built with golang
  golang-prod:
    restart: always
    build: 
      context: golang
      target: prod
    env_file: .env
    depends_on: 
      - postgres

  # front-end built with react
  react-prod:
    restart: always
    build: 
      context: react
      target: prod

# postgres is our primary data store
  postgres:
    build: postgres
    volumes:
      - ./postgres/migrations:/docker-entrypoint-initdb.d/migrations

  # nginx is used for ssl termination
  nginx-prod:
    restart: always
    build: 
      context: nginx
      target: prod
    depends_on: 
      - golang-prod
      - react-prod
      - postgres
    # volumes:
    #  - ../certs-data:/data/letsencrypt
    #  - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"